import { OrganizationRole } from '@prisma/client';
import { OrganizationPermission } from './permission.types';

export const ROLE_PERMISSIONS_MAP: Record<OrganizationRole, OrganizationPermission[]> = {
  OWNER: [
    'organization.read',
    'organization.update',
    'organization.delete',
    'organization.transfer_ownership',
    'organization.members.read',
    'organization.members.invite',
    'organization.members.update',
    'organization.members.remove',
    'organization.teams.read',
    'organization.teams.create',
    'organization.teams.update',
    'organization.teams.delete',
    'organization.teams.manage_members',
    'organization.settings.read',
    'organization.settings.update',
    'organization.domains.manage',
    'organization.billing.read',
    'organization.billing.manage',
    'organization.analytics.read',
    'organization.audit.read',
    'trainer.clients.read',
    'trainer.clients.manage',
    'workouts.read',
    'workouts.create',
    'workouts.update',
    'workouts.assign',
    'nutrition.read',
    'nutrition.manage',
    'media.read',
    'media.manage',
  ],

  ADMIN: [
    'organization.read',
    'organization.update',
    'organization.members.read',
    'organization.members.invite',
    'organization.members.update',
    'organization.members.remove',
    'organization.teams.read',
    'organization.teams.create',
    'organization.teams.update',
    'organization.teams.delete',
    'organization.teams.manage_members',
    'organization.settings.read',
    'organization.settings.update',
    'organization.analytics.read',
    'organization.audit.read',
    'trainer.clients.read',
    'trainer.clients.manage',
    'workouts.read',
    'workouts.create',
    'workouts.update',
    'workouts.assign',
    'nutrition.read',
    'nutrition.manage',
    'media.read',
    'media.manage',
  ],

  MANAGER: [
    'organization.read',
    'organization.members.read',
    'organization.teams.read',
    'organization.teams.update',
    'organization.teams.manage_members',
    'organization.analytics.read',
    'trainer.clients.read',
    'workouts.read',
    'workouts.create',
    'workouts.update',
    'workouts.assign',
    'nutrition.read',
    'nutrition.manage',
    'media.read',
  ],

  TRAINER: [
    'organization.read',
    'organization.members.read',
    'organization.teams.read',
    'trainer.clients.read',
    'trainer.clients.manage',
    'workouts.read',
    'workouts.create',
    'workouts.update',
    'workouts.assign',
    'nutrition.read',
    'nutrition.manage',
    'media.read',
    'media.manage',
  ],

  MEMBER: [
    'organization.read',
    'organization.members.read',
    'organization.teams.read',
    'workouts.read',
    'nutrition.read',
    'media.read',
  ],

  VIEWER: [
    'organization.read',
    'organization.members.read',
    'organization.teams.read',
    'workouts.read',
    'nutrition.read',
    'media.read',
  ],
};
